### ISSUE TITLE
This script doesn't support your distribution.

### ISSUE THREAD

**Issue by jhansen1** [glokhoff/RaspDAB#5]
Im running the latest Debian Stretch Lite  Raspbian image.

RASPBIAN STRETCH LITE
Minimal image based on Debian Stretch
Version:August 2017
Release date:2017-08-16
Kernel version:4.9

> jhansen@DABserver2:~ $ ./raspdab.sh
> 
> This is the mmbTools installer script for raspbian/debian
> =========================================================
> 
> It will install ODR-DabMux, ODR-AudioEnc, ODR-PadEnc
> and all prerequisites to your machine.
> unknown
> 
> You seem to be running something else than
> debian jessie. This script doesn't
> support your distribution.
> 
> jhansen@DABserver2:~ $ 
>

**Comment by AurelienPicart** [comment]
Modify raspbian.sh script and remplace « jessie » by « stretch ». Next run again the script.

**Comment by LyonelB** [comment]
$  ./raspdab.sh
$ E: Unable to locate package libzmq3

**Comment by JeffMacK** [comment]
> $ ./raspdab.sh
> $ E: Unable to locate package libzmq3

Check ---> https://www.howtoinstall.co/en/debian/stretch/libzmq3-dev

**Comment by yorkie98** [comment]
I am having the same issue..
libzmq3-dev is not the problem. It's libzmq3 (without the -dev) which it fails to find from the following line of the script. These appear to be two separate commands and it's unable the execute the second one.

sudo apt-get -y install libzmq3-dev libzmq3

**Comment by glokhoff** [comment]
2020-04-14 After about 2 years of other projects I returned to RaspDAB. My recommended method to install the necessary software is to simply follow the instructions in the installation guidelines for the 3 software programs (Mux, audio and pad encoder) in the Opendigitalradio github. This will overcome any problems due to changes in the installation requirements in the continued development of the programs.
